version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-similarity-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
